name: CI

on: [pull_request, push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Lint
        run: yarn run lint
      - name: Tests
        run: xvfb-run --auto-servernum yarn run test